<?php
/**
 * Plugin Name:       Lucjan AI Image Disclosure
 * Plugin URI:        https://github.com/lukaszwarcholik/ai-disclosure-labels
 * Description:       Mark an image as generated or modified by AI and show a disclosure label wherever it appears. For the EU AI Act transparency duty.
 * Version:           1.5.0
 * Requires at least: 6.2
 * Requires PHP:      7.4
 * Author:            Lukasz Warcholik
 * Author URI:        https://webdesign.net.pl/
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       lucjan-ai-image-disclosure
 *
 * @package LucjanAiImageDisclosure
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'AIDL_VERSION', '1.5.0' );
define( 'AIDL_FILE', __FILE__ );
define( 'AIDL_PATH', plugin_dir_path( __FILE__ ) );
define( 'AIDL_URL', plugin_dir_url( __FILE__ ) );

/**
 * The flag lives on the ATTACHMENT, not on the post.
 *
 * An image marked once stays marked everywhere it is used - as a featured
 * image, inside content, in a gallery. If the flag lived on the post, the
 * same file used elsewhere would silently lose its label.
 */
define( 'AIDL_META', '_aidl_is_ai' );

/**
 * How the image was made: '' (not AI), 'generated' or 'modified'.
 *
 * The AI Act asks for a disclosure on both fully synthetic images and real
 * ones an AI has altered, but those are not the same claim and a reader can
 * tell the difference - so they get their own label. AIDL_META above stays
 * as the yes/no flag: it is what 1.0 wrote, what other code may already
 * read, and what the file-name map and the quick checks use.
 */
define( 'AIDL_META_MODE', '_aidl_mode' );
define( 'AIDL_OPTION', 'aidl_settings' );

require_once AIDL_PATH . 'includes/settings.php';
require_once AIDL_PATH . 'includes/media.php';
require_once AIDL_PATH . 'includes/frontend.php';
require_once AIDL_PATH . 'includes/catch-all.php';

/**
 * Default settings. Kept in one place so the settings page, the defaults on
 * activation and the readers never drift apart.
 *
 * @return array
 */
function aidl_defaults() {
	return array(
		'label_text'          => __( 'Image generated by AI', 'lucjan-ai-image-disclosure' ),
		'badge_text'          => __( 'AI', 'lucjan-ai-image-disclosure' ),
		'label_text_modified' => __( 'Image modified using AI', 'lucjan-ai-image-disclosure' ),
		'badge_text_modified' => __( 'AI', 'lucjan-ai-image-disclosure' ),
		'show_single'  => 1,
		'show_archive' => 1,
		'catch_all'    => 0,
		'placement'    => 'auto',
		'style'        => 'auto',
		'font_size'    => 13,
		'opacity'      => 65,
		'delete_data'  => 0,
	);
}

/**
 * One setting value, already merged with defaults.
 *
 * @param string $key Setting key.
 * @return mixed
 */
function aidl_get( $key ) {

	$zapisane = get_option( AIDL_OPTION, array() );
	$wszystkie = wp_parse_args( is_array( $zapisane ) ? $zapisane : array(), aidl_defaults() );

	return isset( $wszystkie[ $key ] ) ? $wszystkie[ $key ] : null;
}

/**
 * Where the label sits.
 *
 * 'auto' is the default and stays the recommendation: a caption reads well
 * under a large image and is unreadable squeezed onto a thumbnail, so the
 * plugin picks per image instead of forcing one answer on every size.
 *
 * @return array placement => label
 */
function aidl_placements() {

	return array(
		'auto'         => __( 'Automatic - caption under large images, badge on thumbnails', 'lucjan-ai-image-disclosure' ),
		'below'        => __( 'Always under the image', 'lucjan-ai-image-disclosure' ),
		'bottom-right' => __( 'On the image - bottom right', 'lucjan-ai-image-disclosure' ),
		'bottom-left'  => __( 'On the image - bottom left', 'lucjan-ai-image-disclosure' ),
		'top-right'    => __( 'On the image - top right', 'lucjan-ai-image-disclosure' ),
		'top-left'     => __( 'On the image - top left', 'lucjan-ai-image-disclosure' ),
	);
}

/**
 * How the label looks.
 *
 * @return array style => label
 */
function aidl_styles_list() {

	return array(
		'auto'   => __( 'Automatic - plain text under the image, dark pill on it', 'lucjan-ai-image-disclosure' ),
		'subtle' => __( 'Plain text, no background', 'lucjan-ai-image-disclosure' ),
		'dark'   => __( 'Dark background, white text', 'lucjan-ai-image-disclosure' ),
		'light'  => __( 'White background, dark text', 'lucjan-ai-image-disclosure' ),
		'glass'  => __( 'Translucent, blurred background', 'lucjan-ai-image-disclosure' ),
	);
}

/**
 * The modes an image can be in.
 *
 * @return array mode => label
 */
function aidl_modes() {

	return array(
		''          => __( 'Not AI', 'lucjan-ai-image-disclosure' ),
		'generated' => __( 'Generated by AI', 'lucjan-ai-image-disclosure' ),
		'modified'  => __( 'Modified using AI', 'lucjan-ai-image-disclosure' ),
	);
}

/**
 * How this image was made.
 *
 * Falls back to 'generated' for anything 1.0 marked before the modes
 * existed - an image that was flagged then was flagged as AI-made, and
 * silently unlabelling it on update would be the worst possible failure for
 * a plugin whose whole job is disclosure.
 *
 * @param int $attachment_id Attachment ID.
 * @return string '' , 'generated' or 'modified'
 */
function aidl_mode( $attachment_id ) {

	$attachment_id = (int) $attachment_id;
	$mode          = (string) get_post_meta( $attachment_id, AIDL_META_MODE, true );

	if ( isset( aidl_modes()[ $mode ] ) && '' !== $mode ) {
		return $mode;
	}

	return get_post_meta( $attachment_id, AIDL_META, true ) ? 'generated' : '';
}

/**
 * Is this attachment marked as AI in any way?
 *
 * @param int $attachment_id Attachment ID.
 * @return bool
 */
function aidl_is_ai( $attachment_id ) {
	return '' !== aidl_mode( $attachment_id );
}

/**
 * Write the mode, keeping the yes/no flag in step.
 *
 * @param int    $attachment_id Attachment ID.
 * @param string $mode          '', 'generated' or 'modified'.
 */
function aidl_set_mode( $attachment_id, $mode ) {

	$attachment_id = (int) $attachment_id;
	$mode          = isset( aidl_modes()[ $mode ] ) ? $mode : '';

	if ( '' === $mode ) {
		delete_post_meta( $attachment_id, AIDL_META_MODE );
		delete_post_meta( $attachment_id, AIDL_META );
		return;
	}

	update_post_meta( $attachment_id, AIDL_META_MODE, $mode );
	update_post_meta( $attachment_id, AIDL_META, 1 );
}

register_activation_hook( AIDL_FILE, 'aidl_activate' );
function aidl_activate() {

	if ( false === get_option( AIDL_OPTION ) ) {
		add_option( AIDL_OPTION, aidl_defaults() );
	}
}

/**
 * Settings link on the plugins list - small thing, but every reviewer
 * and every user looks for it there first.
 */
add_filter( 'plugin_action_links_' . plugin_basename( AIDL_FILE ), 'aidl_action_links' );
function aidl_action_links( $links ) {

	$link = '<a href="' . esc_url( admin_url( 'options-general.php?page=lucjan-ai-image-disclosure' ) ) . '">'
		. esc_html__( 'Settings', 'lucjan-ai-image-disclosure' ) . '</a>';

	array_unshift( $links, $link );

	return $links;
}
