<?php
/**
 * Settings page.
 *
 * @package AiDisclosureLabels
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'admin_menu', 'aidl_menu' );
function aidl_menu() {

	add_options_page(
		__( 'AI Disclosure Labels', 'ai-disclosure-labels' ),
		__( 'AI Disclosure Labels', 'ai-disclosure-labels' ),
		'manage_options',
		'ai-disclosure-labels',
		'aidl_settings_page'
	);
}

add_action( 'admin_init', 'aidl_register_settings' );
function aidl_register_settings() {

	register_setting(
		'aidl_group',
		AIDL_OPTION,
		array(
			'type'              => 'array',
			'sanitize_callback' => 'aidl_sanitize',
			'default'           => aidl_defaults(),
		)
	);
}

/**
 * Sanitize everything coming from the form. Nothing is trusted.
 *
 * @param mixed $input Raw input.
 * @return array
 */
function aidl_sanitize( $input ) {

	$defaults = aidl_defaults();

	if ( ! is_array( $input ) ) {
		return $defaults;
	}

	$out = array();

	$out['label_text'] = isset( $input['label_text'] ) && '' !== trim( (string) $input['label_text'] )
		? sanitize_text_field( $input['label_text'] )
		: $defaults['label_text'];

	$out['badge_text'] = isset( $input['badge_text'] ) && '' !== trim( (string) $input['badge_text'] )
		? sanitize_text_field( $input['badge_text'] )
		: $defaults['badge_text'];

	$out['label_text_modified'] = isset( $input['label_text_modified'] ) && '' !== trim( (string) $input['label_text_modified'] )
		? sanitize_text_field( $input['label_text_modified'] )
		: $defaults['label_text_modified'];

	$out['badge_text_modified'] = isset( $input['badge_text_modified'] ) && '' !== trim( (string) $input['badge_text_modified'] )
		? sanitize_text_field( $input['badge_text_modified'] )
		: $defaults['badge_text_modified'];

	$out['placement'] = isset( $input['placement'] ) && isset( aidl_placements()[ $input['placement'] ] )
		? $input['placement']
		: $defaults['placement'];

	$out['style'] = isset( $input['style'] ) && isset( aidl_styles_list()[ $input['style'] ] )
		? $input['style']
		: $defaults['style'];

	$out['show_single']  = empty( $input['show_single'] ) ? 0 : 1;
	$out['show_archive'] = empty( $input['show_archive'] ) ? 0 : 1;
	$out['catch_all']    = empty( $input['catch_all'] ) ? 0 : 1;
	$out['delete_data']  = empty( $input['delete_data'] ) ? 0 : 1;

	$size = isset( $input['font_size'] ) ? (int) $input['font_size'] : $defaults['font_size'];
	$out['font_size'] = max( 9, min( 24, $size ) );

	$opacity = isset( $input['opacity'] ) ? (int) $input['opacity'] : $defaults['opacity'];
	$out['opacity'] = max( 20, min( 100, $opacity ) );

	return $out;
}

function aidl_settings_page() {

	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}
	?>
	<div class="wrap">
		<h1><?php echo esc_html__( 'AI Disclosure Labels', 'ai-disclosure-labels' ); ?></h1>

		<p style="max-width:46em;">
			<?php echo esc_html__( 'Mark an image in the Media Library, or in the AI disclosure panel next to the featured image: generated by AI, or a real image modified using AI. The matching label below is then shown wherever that image appears.', 'ai-disclosure-labels' ); ?>
		</p>

		<form method="post" action="options.php">
			<?php settings_fields( 'aidl_group' ); ?>

			<table class="form-table" role="presentation">
				<tr>
					<th scope="row"><label for="aidl_label_text"><?php echo esc_html__( 'Label text', 'ai-disclosure-labels' ); ?></label></th>
					<td>
						<input name="<?php echo esc_attr( AIDL_OPTION ); ?>[label_text]" id="aidl_label_text" type="text" class="regular-text"
							value="<?php echo esc_attr( aidl_get( 'label_text' ) ); ?>">
						<p class="description"><?php echo esc_html__( 'Shown under the image on single posts and pages.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_badge_text"><?php echo esc_html__( 'Badge text', 'ai-disclosure-labels' ); ?></label></th>
					<td>
						<input name="<?php echo esc_attr( AIDL_OPTION ); ?>[badge_text]" id="aidl_badge_text" type="text" class="small-text"
							value="<?php echo esc_attr( aidl_get( 'badge_text' ) ); ?>">
						<p class="description"><?php echo esc_html__( 'Short badge shown on thumbnails in listings. The full text stays available to screen readers.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_label_text_modified"><?php echo esc_html__( 'Label text for modified images', 'ai-disclosure-labels' ); ?></label></th>
					<td>
						<input name="<?php echo esc_attr( AIDL_OPTION ); ?>[label_text_modified]" id="aidl_label_text_modified" type="text" class="regular-text"
							value="<?php echo esc_attr( aidl_get( 'label_text_modified' ) ); ?>">
						<p class="description"><?php echo esc_html__( 'Used when an image is marked as a real photo altered by AI rather than fully generated.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_badge_text_modified"><?php echo esc_html__( 'Badge text for modified images', 'ai-disclosure-labels' ); ?></label></th>
					<td>
						<input name="<?php echo esc_attr( AIDL_OPTION ); ?>[badge_text_modified]" id="aidl_badge_text_modified" type="text" class="small-text"
							value="<?php echo esc_attr( aidl_get( 'badge_text_modified' ) ); ?>">
					</td>
				</tr>
				<tr>
					<th scope="row"><?php echo esc_html__( 'Where to show', 'ai-disclosure-labels' ); ?></th>
					<td>
						<label><input type="checkbox" name="<?php echo esc_attr( AIDL_OPTION ); ?>[show_single]" value="1" <?php checked( aidl_get( 'show_single' ), 1 ); ?>>
							<?php echo esc_html__( 'Single posts and pages', 'ai-disclosure-labels' ); ?></label><br>
						<label><input type="checkbox" name="<?php echo esc_attr( AIDL_OPTION ); ?>[show_archive]" value="1" <?php checked( aidl_get( 'show_archive' ), 1 ); ?>>
							<?php echo esc_html__( 'Listings and archives', 'ai-disclosure-labels' ); ?></label>
						<p class="description"><?php echo esc_html__( 'Keeping listings on is recommended: that is where a visitor sees the image for the first time.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php echo esc_html__( 'Images the theme prints itself', 'ai-disclosure-labels' ); ?></th>
					<td>
						<label><input type="checkbox" name="<?php echo esc_attr( AIDL_OPTION ); ?>[catch_all]" value="1" <?php checked( aidl_get( 'catch_all' ), 1 ); ?>>
							<?php echo esc_html__( 'Also label images that bypass WordPress image functions', 'ai-disclosure-labels' ); ?></label>
						<p class="description"><?php echo esc_html__( 'Turn this on if your theme or page builder prints image tags straight from its own fields (ACF, sliders, custom templates). The finished page is scanned for the files you have marked. Leave it off if every image on your site is a featured image, a block or a gallery - it is then unnecessary work.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_placement"><?php echo esc_html__( 'Label position', 'ai-disclosure-labels' ); ?></label></th>
					<td>
						<select name="<?php echo esc_attr( AIDL_OPTION ); ?>[placement]" id="aidl_placement">
							<?php foreach ( aidl_placements() as $wartosc => $etykieta ) : ?>
								<option value="<?php echo esc_attr( $wartosc ); ?>" <?php selected( aidl_get( 'placement' ), $wartosc ); ?>>
									<?php echo esc_html( $etykieta ); ?></option>
							<?php endforeach; ?>
						</select>
						<p class="description"><?php echo esc_html__( 'Automatic is recommended: a caption needs room to read, and a thumbnail has none.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_style"><?php echo esc_html__( 'Label style', 'ai-disclosure-labels' ); ?></label></th>
					<td>
						<select name="<?php echo esc_attr( AIDL_OPTION ); ?>[style]" id="aidl_style">
							<?php foreach ( aidl_styles_list() as $wartosc => $etykieta ) : ?>
								<option value="<?php echo esc_attr( $wartosc ); ?>" <?php selected( aidl_get( 'style' ), $wartosc ); ?>>
									<?php echo esc_html( $etykieta ); ?></option>
							<?php endforeach; ?>
						</select>
						<p class="description"><?php echo esc_html__( 'On a photograph, plain text needs a shadow or a background to stay legible - the automatic setting handles that for you.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_font_size"><?php echo esc_html__( 'Label size (px)', 'ai-disclosure-labels' ); ?></label></th>
					<td><input name="<?php echo esc_attr( AIDL_OPTION ); ?>[font_size]" id="aidl_font_size" type="number" min="9" max="24" class="small-text"
						value="<?php echo esc_attr( aidl_get( 'font_size' ) ); ?>"></td>
				</tr>
				<tr>
					<th scope="row"><label for="aidl_opacity"><?php echo esc_html__( 'Label opacity (%)', 'ai-disclosure-labels' ); ?></label></th>
					<td><input name="<?php echo esc_attr( AIDL_OPTION ); ?>[opacity]" id="aidl_opacity" type="number" min="20" max="100" class="small-text"
						value="<?php echo esc_attr( aidl_get( 'opacity' ) ); ?>">
						<p class="description"><?php echo esc_html__( 'Applies to plain text only. A faded box over a photograph is where a disclosure stops being legible, so the backgrounds stay solid.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php echo esc_html__( 'Uninstalling', 'ai-disclosure-labels' ); ?></th>
					<td>
						<label><input type="checkbox" name="<?php echo esc_attr( AIDL_OPTION ); ?>[delete_data]" value="1" <?php checked( aidl_get( 'delete_data' ), 1 ); ?>>
							<?php echo esc_html__( 'Also delete the image marks when the plugin is deleted', 'ai-disclosure-labels' ); ?></label>
						<p class="description"><?php echo esc_html__( 'Off by default. The marks are your statements about your own images, so deleting the plugin keeps them: reinstall it and everything is marked as before. Switch this on only if you want to leave nothing behind.', 'ai-disclosure-labels' ); ?></p>
					</td>
				</tr>
			</table>

			<?php submit_button(); ?>
		</form>

		<hr>
		<p style="max-width:46em;opacity:.75;">
			<?php echo esc_html__( 'This plugin helps you publish a disclosure. It does not decide for you which images require one, and it is not legal advice.', 'ai-disclosure-labels' ); ?>
		</p>
	</div>
	<?php
}
