<?php
$dir = dirname( __DIR__ ) . '/languages';
@mkdir( $dir, 0777, true );

$t = array(
	'A disclosure label will be shown with this image.' => 'Przy tej grafice pojawi się oznaczenie.',
	'AI' => 'AI',
	'AI disclosure' => 'Oznaczenie AI',
	'Badge text' => 'Tekst plakietki',
	'Could not read the image settings.' => 'Nie udało się odczytać ustawień grafiki.',
	'Generated by AI' => 'Wygenerowane przez AI',
	'Image generated by AI' => 'Grafika wygenerowana przez AI',
	'Keeping listings on is recommended: that is where a visitor sees the image for the first time.' => 'Zalecamy zostawić listy włączone — to tam odwiedzający widzi grafikę po raz pierwszy.',
	'Label opacity (%)' => 'Krycie oznaczenia (%)',
	'Label size (px)' => 'Wielkość oznaczenia (px)',
	'Label text' => 'Treść oznaczenia',
	'Listings and archives' => 'Listy i archiwa',
	'Saving failed. Please try again.' => 'Nie udało się zapisać. Spróbuj ponownie.',
	'Settings' => 'Ustawienia',
	'Short badge shown on thumbnails in listings. The full text stays available to screen readers.' => 'Krótka plakietka na miniaturach na listach. Pełna treść zostaje dostępna dla czytników ekranu.',
	'Shown under the image on single posts and pages.' => 'Pokazywane pod grafiką na stronach wpisów i stron.',
	'Single posts and pages' => 'Pojedyncze wpisy i strony',
	'This plugin helps you publish a disclosure. It does not decide for you which images require one, and it is not legal advice.' => 'Wtyczka pomaga opublikować oznaczenie. Nie decyduje za Ciebie, które grafiki go wymagają, i nie jest poradą prawną.',
	'Images the theme prints itself' => 'Grafiki, które motyw drukuje sam',
	'Also label images that bypass WordPress image functions' => 'Oznaczaj też grafiki, które omijają funkcje obrazków WordPressa',
	'Turn this on if your theme or page builder prints image tags straight from its own fields (ACF, sliders, custom templates). The finished page is scanned for the files you have marked. Leave it off if every image on your site is a featured image, a block or a gallery - it is then unnecessary work.' => 'Włącz, jeśli motyw albo builder drukuje tagi obrazków prosto ze swoich pól (ACF, slidery, własne szablony). Gotowa strona jest wtedy przeszukiwana pod kątem plików, które oznaczyłeś. Zostaw wyłączone, jeśli wszystkie grafiki na stronie to obrazki wyróżniające, bloki i galerie — wtedy to zbędna praca.',
	'Not AI' => 'Nie AI',
	'Generated by AI' => 'Wygenerowane przez AI',
	'Modified using AI' => 'Zmodyfikowane przez AI',
	'A disclosure label will be shown with this image. "Modified" is for a real photo an AI has altered.' => 'Przy tej grafice pojawi się oznaczenie. „Zmodyfikowane” jest dla prawdziwego zdjęcia zmienionego przez AI.',
	'Image modified using AI' => 'Grafika zmodyfikowana przez AI',
	'Label text for modified images' => 'Treść oznaczenia dla grafik zmodyfikowanych',
	'Badge text for modified images' => 'Tekst plakietki dla grafik zmodyfikowanych',
	'Used when an image is marked as a real photo altered by AI rather than fully generated.' => 'Używane, gdy grafika jest oznaczona jako prawdziwe zdjęcie zmienione przez AI, a nie w pełni wygenerowana.',
	'Mark an image in the Media Library, or in the AI disclosure panel next to the featured image: generated by AI, or a real image modified using AI. The matching label below is then shown wherever that image appears.' => 'Zaznacz grafikę w Bibliotece mediów albo w panelu „Oznaczenie AI” obok obrazka wyróżniającego: wygenerowana przez AI albo prawdziwa grafika zmodyfikowana przez AI. Odpowiednie oznaczenie z poniższych ustawień pojawi się wszędzie, gdzie ta grafika jest użyta.',
	'generated' => 'wygenerowana',
	'modified' => 'zmodyfikowana',
	'Label position' => 'Pozycja oznaczenia',
	'Label style' => 'Styl oznaczenia',
	'Automatic - caption under large images, badge on thumbnails' => 'Automatycznie — podpis pod dużymi grafikami, plakietka na miniaturach',
	'Always under the image' => 'Zawsze pod grafiką',
	'On the image - bottom right' => 'Na grafice — prawy dolny róg',
	'On the image - bottom left' => 'Na grafice — lewy dolny róg',
	'On the image - top right' => 'Na grafice — prawy górny róg',
	'On the image - top left' => 'Na grafice — lewy górny róg',
	'Automatic - plain text under the image, dark pill on it' => 'Automatycznie — zwykły tekst pod grafiką, ciemna plakietka na niej',
	'Plain text, no background' => 'Zwykły tekst, bez tła',
	'Dark background, white text' => 'Ciemne tło, biały tekst',
	'White background, dark text' => 'Białe tło, ciemny tekst',
	'Translucent, blurred background' => 'Półprzejrzyste tło z rozmyciem',
	'Automatic is recommended: a caption needs room to read, and a thumbnail has none.' => 'Zalecane automatycznie: podpis potrzebuje miejsca, a miniatura go nie ma.',
	'On a photograph, plain text needs a shadow or a background to stay legible - the automatic setting handles that for you.' => 'Na zdjęciu zwykły tekst potrzebuje cienia albo tła, żeby dało się go przeczytać — ustawienie automatyczne robi to za Ciebie.',
	'Applies to plain text only. A faded box over a photograph is where a disclosure stops being legible, so the backgrounds stay solid.' => 'Dotyczy tylko zwykłego tekstu. Wyblakłe tło na zdjęciu to moment, w którym oznaczenie przestaje być czytelne, więc tła zostają kryjące.',
	// Nagłówek wtyczki — WordPress tłumaczy Name i Description przez text domain,
	// więc na liście wtyczek w panelu widać je po polsku.
	'Lucjan AI Image Disclosure' => 'Oznaczenia grafik AI',
	'Mark an image as generated or modified by AI and show a disclosure label wherever it appears. For the EU AI Act transparency duty.' => 'Oznacz grafikę jako wygenerowaną albo zmodyfikowaną przez AI, a oznaczenie pojawi się wszędzie, gdzie jest ona użyta. Pod obowiązek przejrzystości z unijnego AI Act.',
	'Uninstalling' => 'Odinstalowanie',
	'Also delete the image marks when the plugin is deleted' => 'Usuń też oznaczenia grafik przy usuwaniu wtyczki',
	'Off by default. The marks are your statements about your own images, so deleting the plugin keeps them: reinstall it and everything is marked as before. Switch this on only if you want to leave nothing behind.' => 'Domyślnie wyłączone. Oznaczenia to Twoje stwierdzenia o własnych grafikach, więc usunięcie wtyczki ich nie rusza: po ponownej instalacji wszystko jest oznaczone jak wcześniej. Włącz tylko wtedy, gdy nie chcesz zostawić po sobie niczego.',
	'Was this image made with AI?' => 'Czy ta grafika powstała z użyciem AI?',
	'the mark belongs to the file and shows up everywhere it is used.' => 'oznaczenie należy do pliku i pojawia się wszędzie, gdzie jest on użyty.',
	'Where to show' => 'Gdzie pokazywać',
);

// Strings used by assets/editor.js - these go into the JSON for wp.i18n.
$js = array(
	'Could not read the image settings.',
	'Saving failed. Please try again.',
	'Generated by AI',
	'Not AI',
	'Modified using AI',
	'Was this image made with AI?',
	'the mark belongs to the file and shows up everywhere it is used.',
);

$plural = 'nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);';
$date   = gmdate( 'Y-m-d H:i' ) . '+0000';

function po_escape( $s ) {
	return str_replace( array( '\\', '"', "\n", "\t" ), array( '\\\\', '\\"', '\\n', '\\t' ), $s );
}

/* ---------- POT ---------- */
$pot  = "# Copyright (C) 2026 Lukasz Warcholik\n";
$pot .= "# This file is distributed under the GPL-2.0-or-later license.\n";
$pot .= "msgid \"\"\nmsgstr \"\"\n";
$pot .= "\"Project-Id-Version: Lucjan AI Image Disclosure 1.0.0\\n\"\n";
$pot .= "\"Report-Msgid-Bugs-To: https://webdesign.net.pl/\\n\"\n";
$pot .= "\"POT-Creation-Date: {$date}\\n\"\n";
$pot .= "\"MIME-Version: 1.0\\n\"\n";
$pot .= "\"Content-Type: text/plain; charset=UTF-8\\n\"\n";
$pot .= "\"Content-Transfer-Encoding: 8bit\\n\"\n";
$pot .= "\"X-Domain: lucjan-ai-image-disclosure\\n\"\n\n";

foreach ( array_keys( $t ) as $msgid ) {
	$pot .= 'msgid "' . po_escape( $msgid ) . "\"\nmsgstr \"\"\n\n";
}
file_put_contents( "$dir/lucjan-ai-image-disclosure.pot", $pot );

/* ---------- PO (pl_PL) ---------- */
$po  = "# Polish translation for Lucjan AI Image Disclosure.\n";
$po .= "msgid \"\"\nmsgstr \"\"\n";
$po .= "\"Project-Id-Version: Lucjan AI Image Disclosure 1.0.0\\n\"\n";
$po .= "\"PO-Revision-Date: {$date}\\n\"\n";
$po .= "\"Language: pl_PL\\n\"\n";
$po .= "\"MIME-Version: 1.0\\n\"\n";
$po .= "\"Content-Type: text/plain; charset=UTF-8\\n\"\n";
$po .= "\"Content-Transfer-Encoding: 8bit\\n\"\n";
$po .= "\"Plural-Forms: {$plural}\\n\"\n";
$po .= "\"X-Domain: lucjan-ai-image-disclosure\\n\"\n\n";

foreach ( $t as $msgid => $msgstr ) {
	$po .= 'msgid "' . po_escape( $msgid ) . "\"\n" . 'msgstr "' . po_escape( $msgstr ) . "\"\n\n";
}
file_put_contents( "$dir/lucjan-ai-image-disclosure-pl_PL.po", $po );

/* ---------- MO (pl_PL) ---------- */
$entries = array( '' => "Project-Id-Version: Lucjan AI Image Disclosure 1.0.0\nLanguage: pl_PL\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nPlural-Forms: {$plural}\n" );
foreach ( $t as $k => $v ) {
	$entries[ $k ] = $v;
}
ksort( $entries, SORT_STRING );

$count       = count( $entries );
$ids         = array_keys( $entries );
$strs        = array_values( $entries );
$orig_table  = 28;
$trans_table = $orig_table + 8 * $count;
$offset      = $trans_table + 8 * $count;

$o_desc = '';
$t_desc = '';
$o_data = '';
$t_data = '';

foreach ( $ids as $i => $id ) {
	$o_desc .= pack( 'VV', strlen( $id ), $offset + strlen( $o_data ) );
	$o_data .= $id . "\0";
}
$base = $offset + strlen( $o_data );
foreach ( $strs as $i => $s ) {
	$t_desc .= pack( 'VV', strlen( $s ), $base + strlen( $t_data ) );
	$t_data .= $s . "\0";
}

$mo = pack( 'VVVVVVV', 0x950412de, 0, $count, $orig_table, $trans_table, 0, $offset )
	. $o_desc . $t_desc . $o_data . $t_data;
file_put_contents( "$dir/lucjan-ai-image-disclosure-pl_PL.mo", $mo );

/* ---------- JSON for assets/editor.js ---------- */
$locale_data = array( '' => array( 'domain' => 'messages', 'lang' => 'pl', 'plural-forms' => $plural ) );
foreach ( $js as $msgid ) {
	$locale_data[ $msgid ] = array( $t[ $msgid ] );
}
$json = wp_like_json( array(
	'translation-revision-date' => $date,
	'generator'                 => 'lucjan-ai-image-disclosure build-lang.php',
	'domain'                    => 'messages',
	'locale_data'               => array( 'messages' => $locale_data ),
) );

function wp_like_json( $a ) {
	return json_encode( $a, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );
}

// WordPress looks the file up by md5 of the script's relative path, and
// falls back to md5 of the handle. Ship both names - a few hundred bytes.
foreach ( array( md5( 'assets/editor.js' ), md5( 'aidl-editor' ) ) as $hash ) {
	file_put_contents( "$dir/lucjan-ai-image-disclosure-pl_PL-{$hash}.json", $json );
}

echo "strings: $count\n";
foreach ( glob( "$dir/*" ) as $f ) {
	echo basename( $f ), ' ', filesize( $f ), "\n";
}
