<?php
define( 'ABSPATH', __DIR__ ); define( 'AIDL_META', '_aidl_is_ai' ); define( 'DAY_IN_SECONDS', 86400 );
function esc_attr($s){return htmlspecialchars($s,ENT_QUOTES);} function esc_html($s){return htmlspecialchars($s,ENT_QUOTES);}
function add_action(){} function add_filter(){} function add_shortcode(){}
function apply_filters($t,$v){return $v;} function is_admin(){return false;} function is_feed(){return false;}
function is_singular(){return $GLOBALS['single'];} function wp_basename($p){return basename($p);}
function aidl_placements(){return array('auto'=>'','below'=>'','bottom-right'=>'','bottom-left'=>'','top-right'=>'','top-left'=>'');}
function aidl_styles_list(){return array('auto'=>'','subtle'=>'','dark'=>'','light'=>'','glass'=>'');}
function aidl_get($k){ if(isset($GLOBALS['opt'][$k])) return $GLOBALS['opt'][$k]; $o=array('placement'=>'auto','style'=>'auto','label_text'=>'Image generated by AI','badge_text'=>'AI','label_text_modified'=>'Image modified using AI','badge_text_modified'=>'AI','show_single'=>1,'show_archive'=>1,'catch_all'=>$GLOBALS['catch'],'font_size'=>13,'opacity'=>65);return $o[$k];}
define('AIDL_META_MODE','_aidl_mode');
function aidl_modes(){return array(''=>'Not AI','generated'=>'Generated by AI','modified'=>'Modified using AI');}
function aidl_mode($id){ $m=array(42=>'generated',77=>'modified'); return isset($m[(int)$id])?$m[(int)$id]:''; }
function aidl_is_ai($id){return '' !== aidl_mode($id);}
function get_transient($k){return false;} function set_transient(){} function delete_transient(){}
function get_posts(){return array(42,77);}
function get_post_meta($id,$k,$s){return 42===$id?'2026/10/hero-ai.jpg':'2026/10/karta.webp';}
function wp_get_attachment_metadata($id){return 42===$id?array('sizes'=>array('m'=>array('file'=>'hero-ai-300x200.jpg'))):array('sizes'=>array());}
function wp_register_style(){} function wp_enqueue_style(){} function wp_add_inline_style(){} function wp_doing_ajax(){return false;}
function wp_get_registered_image_subsizes(){return array('thumbnail'=>array('width'=>150,'height'=>150),'medium'=>array('width'=>300,'height'=>300),'medium_large'=>array('width'=>768,'height'=>0),'large'=>array('width'=>1024,'height'=>1024));}
$GLOBALS['catch']=0; $GLOBALS['single']=true;
require '../includes/frontend.php';
require '../includes/catch-all.php';

function spr( $nazwa, $in, $out, $oczekiwane ) {
	$ile = substr_count( $out, '<span class="aidl-label' );
	printf( "%-42s etykiet: %d  %s\n", $nazwa, $ile, $ile === $oczekiwane ? 'OK' : 'BLAD (oczekiwano ' . $oczekiwane . ')' );
}

echo "=== the_content (filtr treści, catch_all WYLACZONY) ===\n";
$c1='<p>Tekst.</p><img class="alignnone size-full wp-image-42" src="/u/hero-ai.jpg" alt=""><p>Dalej.</p>';
spr('klasyczny edytor, oznaczona', $c1, aidl_content_images($c1), 1);
$c2='<img class="wp-image-999" src="/u/inne.jpg">';
spr('klasyczny edytor, nieoznaczona', $c2, aidl_content_images($c2), 0);
$c3='<figure class="wp-block-image size-large"><img src="/u/hero-ai.jpg" class="wp-image-42"><figcaption>Podpis</figcaption></figure>';
$po_bloku = aidl_render_block($c3, array('blockName'=>'core/image'));
spr('blok -> render_block', $c3, $po_bloku, 1);
spr('blok -> render_block + the_content', $c3, aidl_content_images($po_bloku), 1);
$c4='<p>Dwa: <img class="wp-image-42" src="/u/hero-ai.jpg"> i <img class="wp-image-77" src="/u/karta.webp"> koniec.</p>';
spr('dwie oznaczone w jednym akapicie', $c4, aidl_content_images($c4), 2);
$c5='<img src="/u/hero-ai.jpg">';
spr('treść bez klasy wp-image (pomijana)', $c5, aidl_content_images($c5), 0);

echo "\n=== REGRESJA: figure od motywu i male miniatury ===\n";
// Blocksy: post_thumbnail_html zwraca cala figure, nie samo <img>
$fig_motywu = '<figure class="ct-featured-image "><img width="890" height="497" src="/u/hero-ai.jpg" class="attachment-full"><figcaption class="ct-image-caption">Opis od motywu</figcaption></figure>';
$w = aidl_featured_image($fig_motywu, 766, 42, 'full');
$poz_img = strpos($w, '<img');
$poz_lab = strpos($w, 'aidl-label');
$poz_cap = strpos($w, 'figcaption');
echo 'etykieta zaraz po <img>, przed figcaption: ' . ( $poz_img < $poz_lab && $poz_lab < $poz_cap ? 'OK' : 'BLAD' ) . "\n";
echo 'figure zostala elementem zewnetrznym (nie owinieta w span): ' . ( 0 === strpos($w, '<figure') ? 'OK' : 'BLAD' ) . "\n";
echo 'jedna etykieta: ' . ( 1 === substr_count($w,'<span class="aidl-label') ? 'OK' : 'BLAD' ) . "\n";
echo "\n";
// miniatura 150px w widgecie na stronie pojedynczej -> plakietka, nie podpis
$mini = aidl_attachment_image('<img width="150" height="150" src="/u/hero-ai-150x150.jpg">', 42, 'thumbnail');
echo 'miniatura 150px na single -> plakietka: ' . ( false !== strpos($mini,'aidl-label--badge') ? 'OK' : 'BLAD' ) . "\n";
$duza = aidl_attachment_image('<img width="890" height="497" src="/u/hero-ai.jpg">', 42, 'full');
echo 'duza grafika na single -> podpis: ' . ( false === strpos($duza,'badge') ? 'OK' : 'BLAD' ) . "\n";
$tab = aidl_attachment_image('<img src="/u/hero-ai.jpg">', 42, array(200,200));
echo 'rozmiar jako tablica 200x200 -> plakietka: ' . ( false !== strpos($tab,'aidl-label--badge') ? 'OK' : 'BLAD' ) . "\n";
// link wokol obrazka (widget najnowszych wpisow)
$link = '<a href="/x"><img width="150" src="/u/hero-ai-150x150.jpg" class="wp-image-42"></a>';
$lw = aidl_content_images($link);
echo 'img w <a>: span owija obrazek, nie link: ' . ( 0 === strpos($lw,'<a ') && false !== strpos($lw,'aidl-label--badge') ? 'OK' : 'BLAD' ) . "\n";

echo "\n=== bufor strony (catch_all WLACZONY) ===\n";
$GLOBALS['catch']=1;
$b1='<main><img src="/u/hero-ai.jpg"><img src="/u/karta.webp"><img src="/u/zwykle.jpg"></main>';
spr('ACF: dwie oznaczone, jedna nie', $b1, aidl_buffer_filter($b1), 2);
$b2='<picture><source srcset="/u/hero-ai.jpg.webp"><img src="/u/hero-ai.jpg"></picture>';
spr('picture z WebP', $b2, aidl_buffer_filter($b2), 1);
$b3=aidl_featured_image('<img src="/u/hero-ai-300x200.jpg" class="wp-post-image">',10,42,'medium');
spr('featured + bufor (marker)', $b3, aidl_buffer_filter($b3), 1);
$b4='<span class="aidl-image"><img src="/u/hero-ai.jpg"><span class="aidl-label">x</span></span>';
spr('z cache, bez markera', $b4, aidl_buffer_filter($b4), 1);
$b5='<figure class="aidl-figure wp-block-image"><img src="/u/hero-ai.jpg"><figcaption>'.str_repeat('a',90).'</figcaption><span class="aidl-label">x</span></figure>';
spr('figure z cache, dlugi figcaption', $b5, aidl_buffer_filter($b5), 1);
echo "\nmarker zostal w wyjsciu? ", ( false !== strpos( aidl_buffer_filter($b3), 'data-aidl-done' ) ? 'TAK (blad)' : 'nie' ), "\n";


echo "\n=== TRYBY: wygenerowana vs zmodyfikowana ===\n";
$GLOBALS['single']=true; $GLOBALS['catch']=0;
$g = aidl_content_images('<img class="wp-image-42" src="/u/hero-ai.jpg">');
$m = aidl_content_images('<img class="wp-image-77" src="/u/karta.webp">');
echo 'generated -> tekst: ' . ( false !== strpos($g,'Image generated by AI') ? 'OK' : 'BLAD' ) . ', klasa: ' . ( false !== strpos($g,'aidl-label--generated') ? 'OK' : 'BLAD' ) . "\n";
echo 'modified  -> tekst: ' . ( false !== strpos($m,'Image modified using AI') ? 'OK' : 'BLAD' ) . ', klasa: ' . ( false !== strpos($m,'aidl-label--modified') ? 'OK' : 'BLAD' ) . "\n";
$GLOBALS['single']=false;
$mb = aidl_content_images('<img class="wp-image-77" src="/u/karta.webp">');
echo 'modified jako plakietka: title z pelnym tekstem: ' . ( false !== strpos($mb,'title="Image modified using AI"') ? 'OK' : 'BLAD' ) . "\n";
$GLOBALS['single']=true;
echo 'nieoznaczona (brak trybu) nie dostaje nic: ' . ( '<img class="wp-image-5" src="/u/x.jpg">' === aidl_content_images('<img class="wp-image-5" src="/u/x.jpg">') ? 'OK' : 'BLAD' ) . "\n";


echo "\n=== POZYCJA I STYL ===\n";
$GLOBALS['single']=true; $GLOBALS['catch']=0;
$daj = function() { return aidl_content_images('<img width="900" class="wp-image-42" src="/u/hero-ai.jpg">'); };

$GLOBALS['opt']=array('placement'=>'auto','style'=>'auto');
$h=$daj(); echo 'auto na single -> podpis, styl subtle: ' . ( false===strpos($h,'badge') && false!==strpos($h,'aidl-style-subtle') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['single']=false;
$h=$daj(); echo 'auto na liscie -> plakietka, styl dark, lewy dolny: ' . ( false!==strpos($h,'aidl-label--badge') && false!==strpos($h,'aidl-style-dark') && false!==strpos($h,'aidl-at-bottom-left') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['single']=true;
$GLOBALS['opt']=array('placement'=>'below','style'=>'auto');
$h=$daj(); echo 'below na single -> podpis: ' . ( false===strpos($h,'badge') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['single']=false;
$h=$daj(); echo 'below na liscie -> tez podpis: ' . ( false===strpos($h,'badge') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['single']=true;
$GLOBALS['opt']=array('placement'=>'top-right','style'=>'glass');
$h=$daj(); echo 'top-right + glass na single -> plakietka w rogu: ' . ( false!==strpos($h,'aidl-at-top-right') && false!==strpos($h,'aidl-style-glass') && false!==strpos($h,'aidl-label--badge') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['opt']=array('placement'=>'bottom-right','style'=>'light');
$h=$daj(); echo 'bottom-right + light: ' . ( false!==strpos($h,'aidl-at-bottom-right') && false!==strpos($h,'aidl-style-light') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['opt']=array('placement'=>'auto','style'=>'auto');
$mini = aidl_attachment_image('<img width="150" src="/u/hero-ai-150x150.jpg">', 42, 'thumbnail');
echo 'auto + miniatura 150px -> plakietka: ' . ( false!==strpos($mini,'aidl-label--badge') ? 'OK':'BLAD' ) . "\n";
$GLOBALS['opt']=array('placement'=>'bzdura','style'=>'bzdura');
$h=$daj(); echo 'bledne wartosci nie wywalaja: ' . ( false!==strpos($h,'aidl-label') ? 'OK':'BLAD' ) . "\n";
